### ISSUE TITLE
React Framework

### ISSUE THREAD

**Issue by lucasilverentand** [onezerocompany/zero-ui#52]
We need a react based framework for building websites.

```[tasklist]
### Tasks
- [ ] https://github.com/onezerocompany/zero-ui/issues/53
- [ ] https://github.com/onezerocompany/zero-ui/issues/58
- [ ] https://github.com/onezerocompany/zero-ui/issues/56
- [ ] https://github.com/onezerocompany/zero-ui/issues/57
- [ ] https://github.com/onezerocompany/zero-ui/issues/60
- [ ] https://github.com/onezerocompany/zero-ui/issues/61
- [ ] https://github.com/onezerocompany/zero-ui/issues/59
- [ ] https://github.com/onezerocompany/zero-ui/issues/62
- [ ] https://github.com/onezerocompany/zero-ui/issues/63
```
